#!/bin/csh

set echo_style = both

switch(`uname`)
case    'FreeBSD':
    if ( -e /usr/jb-ports ) then
	rm -rf /usr/jb-ports
    endif
    
    breaksw
    
case    'Darwin':
    if ( ! -e /opt/local ) then
	echo "===================================================================="
	echo "You don't seem to have MacPorts installed.  You must first download"
	echo "and install the MacPorts base from http://www.macports.org, and then"
	echo "run this script again."
	echo "===================================================================="
	exit 1
    endif
    
    # Remove old frameworks
    echo 'Removing old frameworks...'
    rm -rf /opt/local/MacPorts-JB /opt/local/MacPorts_JB /opt/local/MacPorts_MRI
    breaksw
    
default:
    echo "$0 : Error: Unknown OS: `uname`"
    exit 1

endsw

