#!/bin/sh -e

wip_ports_dir='/usr/wip'
    
if [ ! -e $wip_ports_dir ]; then
    printf "Sourceforge username? [anonymous] "
    read username
    cd /usr
    if [ 0$username = 0 ]; then
	svn checkout http://svn.code.sf.net/p/freebsdwip/code/ wip
    else
	svn checkout --username=$username svn+ssh://$username@svn.code.sf.net/p/freebsdwip/code/ wip
    fi
else
    cd $wip_ports_dir
    ./clean-all
    svn up
fi

sed -i '' -e 's|^DEV_WARNING+=.*"Not validating first|# &|' /usr/ports/Mk/bsd.sanity.mk

cd $wip_ports_dir/ports-mgmt/update-wip-ports
make -DBATCH deinstall distclean reinstall
make distclean

cat << EOM

*********************************************************
You can now install any of the ports added above using:

cd $wip_ports_dir/<category>/<portname>
make install
*********************************************************
EOM

