.TH UPDATE-WIP-PORTS 1
.SH NAME    \" Section header
.PP

update-wip-ports - Download and install frameworks for work-in-progress ports

.SH SYNOPSIS
.PP
.nf 
.na 
update-wip-ports
.ad
.fi

.SH "DESCRIPTION"
The
.B update-wip-ports
script downloads and installs frameworks for development versions of various
FreeBSD ports.  These are frameworks for ports that have not been committed
to the official ports tree.

The software installed via the ports is not affected by update-wip-ports
in any way: Only the frameworks are updated.  To upgrade software
installed via these ports:

1. Remove the software via the ports system (e.g. "make deinstall" or
pkg_delete)

2. Run update-wip-ports

3. Reinstall the port using "make install" or "port install".

.SH "SEE ALSO"
genplist(1), svn(1)

.SH AUTHOR
.nf
.na
Jason W. Bacon

