.TH UPDATE-JB-PORTS 1
.SH NAME    \" Section header
.PP

update-jb-ports - Download and install frameworks for Jason's development ports

.SH SYNOPSIS
.PP
.nf 
.na 
update-jb-ports
.ad
.fi

.SH "DESCRIPTION"
The
.B update-jb-ports
script downloads and installs frameworks for development versions of
Jason Bacon's FreeBSD ports or MacPorts.  These are frameworks for
ports that have not been committed to the official ports tree.

The script removes old versions of the frameworks, including work directories,
before installing the new frameworks.

The software installed via the ports is not affected by update-jb-ports
in any way: Only the frameworks are replaced.  To upgrade software
installed via these ports:

1. Remove the software via the ports system (e.g. "make deinstall" on FreeBSD
or "port uninstall" on MacPorts.)

2. Run update-jb-ports

3. Reinstall the port using "make install" or "port install".

.SH "SEE ALSO"
remove-jb-ports(1), genplist(1)

.SH AUTHOR
.nf
.na
Jason W. Bacon

