#!/bin/sh -e

if [ 0$1 = 0-y ]; then
    sure=y
else
    printf "This will disable security checks.  Are you sure?  y/[n] "
    read sure
fi

if [ -z $PORTSDIR ]; then
    PORTSDIR=/usr/ports
fi

if [ 0$sure = 0y ]; then
    sed -i '' -e 's|^DEV_WARNING+=.*"Not validating|#&|' \
	$PORTSDIR/Mk/bsd.sanity.mk
    sed -i '' -e 's|^DEV_WARNING+=.*"It looks like the ${d} depends|#&|' \
	$PORTSDIR/Mk/bsd.port.mk
    sed -i '' -e 's|^DEV_ERROR+=.*contains unsupported relative|#&|' \
	$PORTSDIR/Mk/bsd.sanity.mk
fi

