#!/bin/sh -e

usage()
{
    cat << EOM
Usage: wip-reinstall-port [-[n]u] [-[n]r] -b portname [portname ...]

-u  = run wip-update first
-r  = remove distfile before rebuilding
-nu = do not run wip-update first
-nr = do not remove distfile before rebuilding
-b  = Build in batch mode (no options dialogs)
EOM
    exit $EX_USAGE
}

EX_USAGE=64

if [ $# -lt 1 ]; then
    usage
fi

while echo $1 | grep -q -e '^-'; do
    case $1 in
    -r)
	remove='y'
	;;
    -u)
	update='y'
	;;
    -nr)
	remove='n'
	;;
    -nu)
	update='n'
	;;
    -b)
	make_flags='-DBATCH'
	;;
    *)
	usage
	;;
    esac
    shift
done

case $(uname) in
FreeBSD)
    : ${PORTSDIR:=/usr/ports}
    ;;

DragonFly)
    : ${PORTSDIR:=/usr/dports}
    ;;

*)
    printf "$0: Not supported on $(uname).\n"
    exit 1
    ;;

esac

if [ x$update = x ]; then
    printf "Run wip-update first? [y]/n "
    read update
fi

if [ x$remove = x ]; then
    printf "Remove distfile? y/[n] "
    read remove
fi

if [ x$update != x'n' ]; then
    cd
    wip-update
fi

for portname in $@; do
    cd $PORTSDIR/wip/$portname
    if [ x$remove = xy ]; then
	make distclean
    else
	make clean
    fi
    
    make deinstall
    make clean
    make rmconfig
    make $make_flags reinstall
done
