#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2016-02-02  Charlie &   Begin
##########################################################################

usage()
{
    cat << EOM

Usage: $0 port all|pattern|jailname [jailname ...]

Examples:

    # All jails
    wip-poudriere-test boost-libs all

    # All jails with 10-3 in name
    wip-poudriere-test boost-libs 10-3

    # All jails with amd64 in name
    wip-poudriere-test boost-libs amd64

    # Two specific jails
    wip-poudriere-test boost-libs 10-3-amd64 11-0-i386

EOM
    printf "Available jails:\n\n"
    poudriere jail -ln
    exit 1
}


##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}


##########################################################################
#   Main
##########################################################################

if [ $# -lt 2 ]; then
    usage
fi

port=$1
jails=$2
umask 022

if [ -z $PORTSDIR ]; then
    PORTSDIR=/usr/ports
fi

# FIXME: Don't hard-code poudriere prefix
POUDRIERE=/usr/local/poudriere
chmod -R a+rX $PORTSDIR/wip
rsync -av --delete $PORTSDIR/wip $POUDRIERE/ports/default/
sed -i '' -e 's|wayland www|wayland wip www|g' \
    $POUDRIERE/ports/default/Mk/bsd.port.mk

port-poudriere-test wip/$port $jails
