#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2017-03-23  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 portname\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

portname=$1

case $(uname) in
FreeBSD)
    : ${PORTSDIR:=/usr/ports}
    ;;

DragonFly)
    : ${PORTSDIR:=/usr/dports}
    ;;

*)
    printf "$0: Not supported on $(uname).\n"
    exit 1
    ;;

esac

cd $PORTSDIR/wip
port create $portname
cd $portname
wip-edit
