#!/bin/sh -e

case $(uname) in
FreeBSD)
    : ${PORTSDIR:=/usr/ports}
    ;;

DragonFly)
    : ${PORTSDIR:=/usr/dports}
    ;;

*)
    printf "$0: Not supported on $(uname).\n"
    exit 1
    ;;

esac

cd $PORTSDIR/wip
for dir in *; do
    if [ -e $dir/Makefile ]; then
	categories=`awk -F = '$1 == "CATEGORIES" { print $2 }' $dir/Makefile`
	committed=0
	for category in $categories; do
	    if [ $category != wip ] && [ -e $PORTSDIR/$category/$dir ]; then
		committed=1
		printf "Found $category/$dir\n"
		egrep '^PORTVERSION=|^DISTVERSION=' \
		    $PORTSDIR/wip/$dir/Makefile \
		    $PORTSDIR/$category/$dir/Makefile
		read -p "Diff? y/[n] " diff
		if [ 0$diff = 0y ]; then
		    diff -ruN \
			$PORTSDIR/$category/$dir \
			$PORTSDIR/wip/$dir | more
		    printf "\nDependent ports:\n"
		    fgrep wip/$dir */Makefile || true
		    read -p "Remove? y/[n] " remove
		    if [ 0$remove = 0y ]; then
			svn rm $dir
			svn ci -m "${dir}: Remove obsolete port"
		    fi
		fi
	    fi
	done
	if [ $committed = 0 ]; then
	    printf "No committed version of $dir.\n"
	fi
    fi
done

