#!/bin/sh -e

##########################################################################
#   Script description:
#       Generate a skeletal new port and begin the edit process
#       
#   History:
#   Date        Name        Modification
#   2017-03-23  Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0 portname category maintainer\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 3 ]; then
    usage
fi

portname=$1
category=$2
maintainer=$3

case $(uname) in
FreeBSD)
    : ${PORTSDIR:=/usr/ports}
    ;;

DragonFly)
    : ${PORTSDIR:=/usr/dports}
    ;;

*)
    printf "$0: Not supported on $(uname).\n"
    exit 1
    ;;

esac

cd $PORTSDIR/wip
port-create $portname $category $maintainer
cd $portname
wip-edit
