#!/bin/sh -e

##########################################################################
#   Script description:
#       Poudriere test a WIP port
#       
#   History:
#   Date        Name        Modification
#   2016-02-02  J Bacon     Begin
##########################################################################

usage()
{
    cat << EOM

Usage: $0 port all|pattern|jailname [jailname ...]

Examples:

    # All jails
    wip-poudriere-test boost-libs all

    # All jails with 10-3 in name
    wip-poudriere-test boost-libs 10-3

    # All jails with amd64 in name
    wip-poudriere-test boost-libs amd64

    # Two specific jails
    wip-poudriere-test boost-libs 10-3-amd64 11-0-i386

EOM
    printf "Available jails:\n\n"
    poudriere jail -ln
    exit 1
}


##########################################################################
#   Function description:
#       Pause until user presses return
##########################################################################

pause()
{
    local junk
    
    printf "Press return to continue..."
    read junk
}


##########################################################################
#   Main
##########################################################################

if [ $# -lt 2 ]; then
    usage
fi

invoked_as=$(basename $0)
port=$1
shift
jails="$@"
umask 022

printf "Update wip first? [y]/n "
read update_wip
if [ 0"$update_wip" != 0n ]; then
    wip-update
fi

case $(uname) in
FreeBSD)
    : ${PORTSDIR:=/usr/ports}
    ;;

DragonFly)
    : ${PORTSDIR:=/usr/dports}
    ;;

*)
    printf "$0: Not supported on $(uname).\n"
    exit 1
    ;;

esac

# In case of restrictive umask during prior downloads
chmod -R a+rX $PORTSDIR/distfiles

# FIXME: Don't hard-code poudriere prefix
POUDRIERE=/usr/local/poudriere
chmod -R a+rX $PORTSDIR/wip
rsync -av --delete --exclude work $PORTSDIR/wip $POUDRIERE/ports/default/

# Existence of wip/Mk makes poudriere error out for non-existent port.
# We don't currently use overlays for poudriere, but rely on the old method
# $POUDRIERE/ports/default/Mk/bsd.local.mk.
rm -rf $POUDRIERE/ports/default/wip/Mk

auto-append-line 'VALID_CATEGORIES+=wip' \
	$POUDRIERE/ports/default/Mk/bsd.local.mk $0
if [ $invoked_as = wip-poudriere-test ]; then
    port-poudriere-test wip/$port $jails
elif [ $invoked_as = wip-poudriere-pkg ]; then
    port-poudriere-pkg wip/$port $jails
else
    printf "$0: Invalid invocation.\n" >> /dev/stderr
    exit 1
fi
